name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies manually
      run: |
        pip install future matplotlib pandas requests seaborn jupyter-book scikit-learn ipywidgets
        pip install cartopy==0.22
        pip install pmagpy==4.2.106
        pip install -e ./smpsite
        
    # - name: Create environment with micromamba 🐍🖤
    #   uses: mamba-org/setup-micromamba@v1
    #   with: 
    #     micromamba-version: '1.3.1-0'
    #     environment-file: ./environment.yml
    #     environment-name: paleosampling
    #     init-shell: bash
    #     cache-environment: true
    
    # Build the book
    - name: Build the book 📘
      run: |
        jupyter-book build .
      # env:
      #   PYTHON : /home/runner/micromamba/envs/paleosampling/bin/python
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
